version: "3"
services:
  postgresdb:
    image: postgres:12.3
    container_name: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: haxul
      POSTGRES_PASSWORD: password
      POSTGRES_DB: player-db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432